#!/usr/bin/env bash
set -Eeuo pipefail

# make libvirt happy
# https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/libvirt/libvirt-8.4.0.ebuild
# ditto rewrite_docker
module_flags \
	DM_MULTIPATH \
	DM_SNAPSHOT \
	MACVLAN \
	NET_CLS_CGROUP \
	VETH \
	BRIDGE \
	BRIDGE_NETFILTER \
	IP_NF_IPTABLES \
	IP_NF_FILTER \
	NF_CONNTRACK \
	IP_NF_NAT \
	IP_NF_TARGET_MASQUERADE \
	NETFILTER_XTABLES \
	BRIDGE_NF_EBTABLES \
	BRIDGE_EBT_MARK_T \
	NETFILTER_XT_CONNMARK \
	NETFILTER_XT_MARK \
	NETFILTER_XT_TARGET_CHECKSUM \
	IP_NF_MANGLE \
	IP6_NF_IPTABLES \
	IP6_NF_FILTER \
	IP6_NF_MANGLE \
	IP6_NF_NAT \
	BRIDGE_EBT_T_NAT \
	IP_NF_TARGET_REJECT \
	NET_ACT_POLICE \
	NET_CLS_FW \
	NET_CLS_U32 \
	NET_SCH_HTB \
	NET_SCH_INGRESS \
	NET_SCH_SFQ